deployment:
  name: useragent
  label: useragent
  replicaCount: 1
  configEnabled: true
  containerPort: 8092
  discoveryEnabled: true
  dbEnabled: true
  keycloakClientEnabled: true
  spacesEnabled: false
  secretName: useragent-secret
  image:
    repository: ravv1/useragent
    tag: v1
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "512Mi"
service:
  name: useragent
  type: ClusterIP
  port: 8092
  targetPort: 8092