spring:
  application:
    name: taskManager
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:80/realms/toDoListApp/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager
    password: taskmanager_password
    jakarta:
      persistence:
        jdbc:
  liquibase:
    change-log: classpath:/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8094

logging:
  level:
    root: INFO

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

keycloak:
  auth-server-url: http://localhost
  realm: toDoListApp
  client-id: taskManagerClient
  user-role: USER
  client-secret: AOOhIo0SbWirfHcTrw82f0z0k6YVKOIK

spaces:
  endpoint: https://taskmanager-attachments.ams3.digitaloceanspaces.com
  access-key: DO00DTHRBWN4H8GDTG64
  secret-key: r1BZN7TnjyF+j8TczlbEAGODGXs6rjlw3o4NAiJdcbQ
  bucket: taskmanager-attachments