spring:
  application:
    name: taskManager
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:80/realms/toDoListApp/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager
    password: taskmanager_password
    jakarta:
      persistence:
        jdbc:
  liquibase:
    change-log: classpath:/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    streams:
      application-id: file-processor
    bootstrap-servers: localhost:9094
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="user1"
        password="secretValue";
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit:
        interval:
          ms: 3000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 8094

logging:
  level:
    root: INFO

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

keycloak:
  auth-server-url: http://localhost
  realm: toDoListApp
  client-id: taskManagerClient
  user-role: USER
  client-secret: secretValue

spaces:
  endpoint: https://ams3.digitaloceanspaces.com
  accessKey: DO006Z78WB49GXUAFDGZ
  secretKey: secretValue
  bucketName: taskmanager-attachments