spring:
  application:
    name:
      fileprocesor

  kafka:
    streams:
      application-id: file-processor-${random.uuid}
    bootstrap-servers:
      - localhost:9092
    properties:
      default:
        key:
          sarde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          sarde: org.apache.kafka.common.serialization.Serdes$StringSerde
      commit:
        interval:
          ms: 3000
      processing:
        quarantee: exactly_once_v2

clamAV:
  url: clamav
  port: 3310

spaces:
  endpoint: https://ams3.digitaloceanspaces.com
  accessKey: DO006Z78WB49GXUAFDGZ
  secretKey: secretValue
  bucketName: taskmanager-attachments
