spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edgeserver
    username: edgeserver
    password: edgeserver_password
  security:
    oauth2:
      resourceServer:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/toDoListApp/protocol/openid-connect/certs"
cors:
  allowed-origins: "https://todolist.ooguy.com"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true
server:
  port: 8093