apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    -- Create databases
    CREATE DATABASE useragent;
    CREATE DATABASE edgeserver;

    -- Create users and assign passwords
    CREATE USER useragent WITH PASSWORD 'useragent_password';
    CREATE USER edgeserver WITH PASSWORD 'edgeserver_password';

    -- Grant privileges on databases
    GRANT ALL PRIVILEGES ON DATABASE useragent TO useragent;
    GRANT ALL PRIVILEGES ON DATABASE edgeserver TO edgeserver;

    -- Grant privileges on public schema for useragent
    \c useragent;  -- Connect to the useragent database
    GRANT ALL PRIVILEGES ON SCHEMA public TO useragent;

    -- Grant privileges on public schema for edgeserver
    \c edgeserver;  -- Connect to the edgeserver database
    GRANT ALL PRIVILEGES ON SCHEMA public TO edgeserver;
