deployment:
  name: edgeserver
  label: edgeserver
  replicaCount: 1
  configEnabled: true
  containerPort: 8093
  discoveryEnabled: true
  dbEnabled: true
  keycloakClientEnabled: false
  secretName: edgeserver-secret
  image:
    repository: ravv1/edgeserver
    tag: v1
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"
service:
  name: edgeserver
  protocol: https
  type: LoadBalancer
  port: 443
  targetPort: 8093