spring:
  security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost/realms/toDoListApp/protocol/openid-connect/certs
  cloud:
    config:
      import-check:
        enabled: false

server:
  port: 8092
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
keycloak:
  auth-server-url: http://localhost
  realm: toDoListApp
  client-id: userAgentClient
  user-role: USER
  client-secret: 4TtdKgejdLekxDrAbCcmqgAkMAK5uVY1
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  allow-credentials: true