spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: as
    password:
    driver-class-name: org.h2.Drive
  liquibase:
    change-log: classpath:/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE