apiVersion: v2
appVersion: 1.4.1
description: An Open-Source antivirus engine for detecting trojans, viruses, malware
  & other malicious threats. Using Mailu docker image.
home: https://www.clamav.net
icon: https://www.clamav.net/assets/clamav-trademark.png
maintainers:
- name: Wiremind
  url: https://github.com/wiremind/wiremind-helm-charts
name: clamav
sources:
- https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/clamav
- https://github.com/Mailu/Mailu/tree/master/optional/clamav
- https://hub.docker.com/r/mailu/clamav
- https://github.com/Cisco-Talos/clamav-devel
version: 3.2.0
